#!/usr/bin/env ruby
require 'fileutils'

command, args = ENV["SSH_ORIGINAL_COMMAND"].to_s.split
if command.to_s.empty?
  puts "Welcome to dynosaur!"
  puts
  puts "Commands:"
  puts "  check"
  puts "  console"
  puts "  rake ARGS"
  puts
elsif command == 'console'
  Dir.chdir("/app")
  Kernel.exec "console"
elsif command == 'rake'
  Dir.chdir("/app")
  Kernel.exec "rake", args
elsif command == 'check'
  Dir.chdir("/app")
  Kernel.exec "check"
elsif command == 'git-receive-pack'
  args = args[1..-2]
  repodir = File.join(ENV["HOME"], args)
  unless File.directory? repodir
    FileUtils.mkdir_p repodir
    `cd #{repodir} && git init --bare`
    File.open(File.join(repodir, "hooks", "post-receive"), 'w') do |f|
      f.puts "#!/bin/sh"
      f.puts "hook #{args}"
    end
    `chmod +x #{File.join(repodir, "hooks", "post-receive")}`
    #GIT_WORK_TREE=/var/www/www.example.org git checkout -f
  end

  Kernel.exec "git", "shell", "-c", ENV["SSH_ORIGINAL_COMMAND"]
elsif command == 'git-upload-pack'
  Kernel.exec "git", "shell", "-c", command
else
  $stderr.puts "Huh?"
end
